% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/scatterplot.R
\name{kbbd}
\alias{kbbd}
\title{kbbd}
\usage{
kbbd(k, randomize)
}
\arguments{
\item{k, randomize}{}
}
\value{
kbbd
}
\description{
design of box behnken
}
\examples{
k==3
randomize = TRUE
}
